use std::collections::BTreeMap;

use crate::ast::{BinaryOp, Type, UnaryOp};
use crate::ir::{
    IrBookCommand, IrExpr, IrExprKind, IrFunction, IrMacroPlaceholder, IrProgram, IrStmt,
};

#[derive(Debug, Clone)]
pub struct BuildArtifacts {
    pub files: BTreeMap<String, String>,
}

#[derive(Debug, Clone)]
pub struct BackendOptions {
    pub namespace: String,
}

pub fn generate(program: &IrProgram, options: &BackendOptions) -> BuildArtifacts {
    let mut backend = Backend::new(program, options.namespace.clone());
    backend.generate(program);
    BuildArtifacts {
        files: backend.files,
    }
}

struct Backend {
    namespace: String,
    files: BTreeMap<String, String>,
    functions: BTreeMap<String, FunctionInfo>,
    book_commands: BTreeMap<String, IrBookCommand>,
    max_depth: usize,
    block_counter: usize,
    temp_counter: usize,
    macro_counter: usize,
}

#[derive(Debug, Clone)]
struct FunctionInfo {
    params: Vec<(String, Type)>,
    return_type: Type,
    locals: BTreeMap<String, Type>,
}

#[derive(Debug, Clone)]
struct Guard {
    ctrl_slot: String,
    break_slot: Option<String>,
    continue_slot: Option<String>,
}

#[derive(Debug, Clone)]
struct LoopContext {
    break_slot: String,
    continue_slot: String,
    continue_target: String,
}

impl Guard {
    fn for_function(depth: usize, function: &str) -> Self {
        Self {
            ctrl_slot: control_slot(depth, function),
            break_slot: None,
            continue_slot: None,
        }
    }

    fn within_loop(&self, loop_ctx: &LoopContext) -> Self {
        Self {
            ctrl_slot: self.ctrl_slot.clone(),
            break_slot: Some(loop_ctx.break_slot.clone()),
            continue_slot: Some(loop_ctx.continue_slot.clone()),
        }
    }

    fn wrap(&self, command: impl Into<String>) -> String {
        self.wrap_with_options(command, true, true)
    }

    fn wrap_allow_continue(&self, command: impl Into<String>) -> String {
        self.wrap_with_options(command, true, false)
    }

    fn wrap_with_options(
        &self,
        command: impl Into<String>,
        check_break: bool,
        check_continue: bool,
    ) -> String {
        let mut prefix = format!("execute if score {} mcfc matches 0", self.ctrl_slot);
        if check_break {
            if let Some(slot) = &self.break_slot {
                prefix.push_str(&format!(" if score {} mcfc matches 0", slot));
            }
        }
        if check_continue {
            if let Some(slot) = &self.continue_slot {
                prefix.push_str(&format!(" if score {} mcfc matches 0", slot));
            }
        }
        format!("{} run {}", prefix, command.into())
    }
}

impl Backend {
    fn new(program: &IrProgram, namespace: String) -> Self {
        let functions = program
            .functions
            .iter()
            .map(|function| {
                (
                    function.name.clone(),
                    FunctionInfo {
                        params: function
                            .params
                            .iter()
                            .map(|param| (param.name.clone(), param.ty.clone()))
                            .collect(),
                        return_type: function.return_type.clone(),
                        locals: function.locals.clone(),
                    },
                )
            })
            .collect();
        Self {
            namespace,
            files: BTreeMap::new(),
            functions,
            book_commands: program.book_commands.clone(),
            max_depth: program.call_depths.values().copied().max().unwrap_or(0) + 1,
            block_counter: 0,
            temp_counter: 0,
            macro_counter: 0,
        }
    }

    fn generate(&mut self, program: &IrProgram) {
        self.emit_pack_mcmeta();
        self.emit_load_tag();
        self.emit_tick_tag();
        self.emit_setup();
        self.emit_main_entry();
        for function in &program.functions {
            for depth in 0..=self.max_depth {
                self.emit_function_variant(function, depth);
            }
        }
        self.emit_book_runtime();
    }

    fn emit_pack_mcmeta(&mut self) {
        self.files.insert(
            "pack.mcmeta".to_string(),
            "{\n  \"pack\": {\n    \"min_format\": [101, 1],\n    \"max_format\": [101, 1],\n    \"description\": \"Generated by mcfc for Minecraft 26.1.2\"\n  }\n}\n"
                .to_string(),
        );
    }

    fn emit_load_tag(&mut self) {
        self.files.insert(
            "data/minecraft/tags/function/load.json".to_string(),
            format!(
                "{{\n  \"values\": [\n    \"{}:main\"\n  ]\n}}\n",
                self.namespace
            ),
        );
    }

    fn emit_tick_tag(&mut self) {
        self.files.insert(
            "data/minecraft/tags/function/tick.json".to_string(),
            format!(
                "{{\n  \"values\": [\n    \"{}:generated/book/tick\"\n  ]\n}}\n",
                self.namespace
            ),
        );
    }

    fn emit_setup(&mut self) {
        let mut lines = vec![
            "scoreboard objectives add mcfc dummy".to_string(),
            format!(
                "data modify storage {}:runtime frames set value {{}}",
                self.namespace
            ),
        ];

        for depth in 0..=self.max_depth {
            for (function, info) in &self.functions {
                lines.push(format!(
                    "scoreboard players set {} mcfc 0",
                    control_slot(depth, function)
                ));
                for (name, ty) in &info.locals {
                    if matches!(ty, Type::Int | Type::Bool) {
                        lines.push(format!(
                            "scoreboard players set {} mcfc 0",
                            numeric_slot(depth, function, name)
                        ));
                    }
                }
                if matches!(info.return_type, Type::Int | Type::Bool) {
                    lines.push(format!(
                        "scoreboard players set {} mcfc 0",
                        numeric_return_slot(depth, function)
                    ));
                }
            }
        }

        self.files.insert(
            format!(
                "data/{}/function/generated/setup.mcfunction",
                self.namespace
            ),
            lines.join("\n") + "\n",
        );
    }

    fn emit_main_entry(&mut self) {
        let mut lines = vec![format!("function {}:generated/setup", self.namespace)];
        if self.functions.contains_key("main") {
            lines.push(format!(
                "scoreboard players set {} mcfc 0",
                control_slot(0, "main")
            ));
            lines.push(format!(
                "function {}:{}",
                self.namespace,
                self.function_entry_name("main", 0)
            ));
        }
        self.files.insert(
            format!("data/{}/function/main.mcfunction", self.namespace),
            lines.join("\n") + "\n",
        );
    }

    fn emit_book_runtime(&mut self) {
        self.files.insert(
            format!(
                "data/{}/function/generated/book/tick.mcfunction",
                self.namespace
            ),
            format!(
                "execute as @a run function {}:generated/book/tick_player\n",
                self.namespace
            ),
        );

        self.files.insert(
            format!("data/{}/function/generated/book/tick_player.mcfunction", self.namespace),
            format!(
                concat!(
                    "execute unless items entity @s contents minecraft:writable_book[minecraft:custom_data~{{mcfc:{{managed:1b}}}}] run give @s minecraft:writable_book[minecraft:custom_data={{mcfc:{{managed:1b,last_cmd:\"\"}}}},minecraft:item_name='\"MCFC Commands\"',minecraft:writable_book_content={{pages:[{{raw:\"fibb 8\"}}]}}]\n",
                    "execute if data entity @s {{SelectedItem:{{id:\"minecraft:writable_book\",components:{{\"minecraft:custom_data\":{{mcfc:{{managed:1b}}}}}}}}}} run function {}:generated/book/process_mainhand\n"
                ),
                self.namespace
            ),
        );

        self.files.insert(
            format!("data/{}/function/generated/book/process_mainhand.mcfunction", self.namespace),
            format!(
                concat!(
                    "data remove storage {}:runtime book\n",
                    "execute if data entity @s SelectedItem.components.\"minecraft:writable_book_content\".pages[0].raw run data modify storage {}:runtime book.current set from entity @s SelectedItem.components.\"minecraft:writable_book_content\".pages[0].raw\n",
                    "execute unless data entity @s SelectedItem.components.\"minecraft:writable_book_content\".pages[0].raw if data entity @s SelectedItem.components.\"minecraft:writable_book_content\".pages[0] run data modify storage {}:runtime book.current set from entity @s SelectedItem.components.\"minecraft:writable_book_content\".pages[0]\n",
                    "execute store result score $book_cmd_len mcfc run data get storage {}:runtime book.current\n",
                    "execute if score $book_cmd_len mcfc matches 1.. run function {}:generated/book/check_changed with storage {}:runtime book\n"
                ),
                self.namespace,
                self.namespace,
                self.namespace,
                self.namespace,
                self.namespace,
                self.namespace
            ),
        );

        self.files.insert(
            format!("data/{}/function/generated/book/check_changed.mcfunction", self.namespace),
            format!(
                "$execute unless data entity @s {{SelectedItem:{{components:{{\"minecraft:custom_data\":{{mcfc:{{last_cmd:\"$(current)\"}}}}}}}}}} run function {}:generated/book/process_changed\n",
                self.namespace
            ),
        );

        self.files.insert(
            format!("data/{}/function/generated/book/process_changed.mcfunction", self.namespace),
            format!(
                concat!(
                    "function {}:generated/book/tokenize_init\n",
                    "scoreboard players set $book_dispatch_matched mcfc 0\n",
                    "execute store result score $book_token_count mcfc run data get storage {}:runtime book.tokens\n",
                    "execute if score $book_token_count mcfc matches 1.. run data modify storage {}:runtime book.command_name set from storage {}:runtime book.tokens[0]\n",
                    "{}",
                    "execute if score $book_dispatch_matched mcfc matches 0 if score $book_token_count mcfc matches 1.. run tellraw @s \"Unknown book command\"\n",
                    "data modify storage {}:runtime book.update.last_cmd set from storage {}:runtime book.current\n",
                    "item modify entity @s weapon.mainhand {{\"function\":\"minecraft:copy_custom_data\",\"source\":{{\"type\":\"storage\",\"source\":\"{}:runtime\"}},\"ops\":[{{\"source\":\"book.update.last_cmd\",\"target\":\"mcfc.last_cmd\",\"op\":\"replace\"}}]}}\n"
                ),
                self.namespace,
                self.namespace,
                self.namespace,
                self.namespace,
                self.render_book_dispatch_calls(),
                self.namespace,
                self.namespace,
                self.namespace
            ),
        );

        self.files.insert(
            format!("data/{}/function/generated/book/tokenize_init.mcfunction", self.namespace),
            format!(
                concat!(
                    "data modify storage {}:runtime book.tokens set value []\n",
                    "data modify storage {}:runtime book.remaining set from storage {}:runtime book.current\n",
                    "data modify storage {}:runtime book.current_token set value \"\"\n",
                    "function {}:generated/book/tokenize_step\n"
                ),
                self.namespace,
                self.namespace,
                self.namespace,
                self.namespace,
                self.namespace
            ),
        );

        self.files.insert(
            format!("data/{}/function/generated/book/tokenize_step.mcfunction", self.namespace),
            format!(
                concat!(
                    "execute store result score $book_rem_len mcfc run data get storage {}:runtime book.remaining\n",
                    "execute if score $book_rem_len mcfc matches 0 run function {}:generated/book/tokenize_finish\n",
                    "execute if score $book_rem_len mcfc matches 1.. run function {}:generated/book/tokenize_consume\n"
                ),
                self.namespace, self.namespace, self.namespace
            ),
        );

        self.files.insert(
            format!("data/{}/function/generated/book/tokenize_consume.mcfunction", self.namespace),
            format!(
                concat!(
                    "data modify storage {}:runtime book.char set string storage {}:runtime book.remaining 0 1\n",
                    "data modify storage {}:runtime book.remaining set string storage {}:runtime book.remaining 1 1024\n",
                    "execute if data storage {}:runtime {{book:{{char:\" \"}}}} run function {}:generated/book/tokenize_space\n",
                    "execute unless data storage {}:runtime {{book:{{char:\" \"}}}} run function {}:generated/book/tokenize_append\n",
                    "function {}:generated/book/tokenize_step\n"
                ),
                self.namespace,
                self.namespace,
                self.namespace,
                self.namespace,
                self.namespace,
                self.namespace,
                self.namespace,
                self.namespace,
                self.namespace
            ),
        );

        self.files.insert(
            format!("data/{}/function/generated/book/tokenize_space.mcfunction", self.namespace),
            format!(
                concat!(
                    "execute store result score $book_tok_len mcfc run data get storage {}:runtime book.current_token\n",
                    "execute if score $book_tok_len mcfc matches 1.. run function {}:generated/book/tokenize_push\n"
                ),
                self.namespace, self.namespace
            ),
        );

        self.files.insert(
            format!("data/{}/function/generated/book/tokenize_append.mcfunction", self.namespace),
            format!(
                "data modify storage {}:runtime book.current_token append string storage {}:runtime book.char 0 1\n",
                self.namespace, self.namespace
            ),
        );

        self.files.insert(
            format!("data/{}/function/generated/book/tokenize_push.mcfunction", self.namespace),
            format!(
                concat!(
                    "data modify storage {}:runtime book.tokens append from storage {}:runtime book.current_token\n",
                    "data modify storage {}:runtime book.current_token set value \"\"\n"
                ),
                self.namespace, self.namespace, self.namespace
            ),
        );

        self.files.insert(
            format!("data/{}/function/generated/book/tokenize_finish.mcfunction", self.namespace),
            format!(
                concat!(
                    "execute store result score $book_tok_len mcfc run data get storage {}:runtime book.current_token\n",
                    "execute if score $book_tok_len mcfc matches 1.. run function {}:generated/book/tokenize_push\n"
                ),
                self.namespace, self.namespace
            ),
        );

        let max_args = self
            .book_commands
            .values()
            .map(|command| command.arg_count)
            .max()
            .unwrap_or(0);
        for index in 1..=max_args {
            self.files.insert(
                format!(
                    "data/{}/function/generated/book/parse_arg_{}.mcfunction",
                    self.namespace, index
                ),
                format!("$scoreboard players set $book_arg{} mcfc $(arg)\n", index),
            );
        }

        let book_commands: Vec<_> = self.book_commands.values().cloned().collect();
        for command in &book_commands {
            self.emit_book_dispatch_function(command);
        }
    }

    fn emit_function_variant(&mut self, function: &IrFunction, depth: usize) {
        let path = self.function_entry_path(&function.name, depth);
        let mut lines = Vec::new();
        let guard = Guard::for_function(depth, &function.name);
        self.emit_stmt_list(function, depth, &function.body, &guard, None, &mut lines);
        self.files.insert(
            path,
            if lines.is_empty() {
                "# empty function\n".to_string()
            } else {
                lines.join("\n") + "\n"
            },
        );
    }

    fn emit_stmt_list(
        &mut self,
        function: &IrFunction,
        depth: usize,
        stmts: &[IrStmt],
        guard: &Guard,
        loop_ctx: Option<&LoopContext>,
        lines: &mut Vec<String>,
    ) {
        for stmt in stmts {
            match stmt {
                IrStmt::Let { name, value, .. } | IrStmt::Assign { name, value } => {
                    let mut stmt_lines = Vec::new();
                    self.compile_expr_into_named_slot(
                        function,
                        depth,
                        value,
                        name,
                        &mut stmt_lines,
                    );
                    self.extend_guarded(lines, guard, stmt_lines);
                }
                IrStmt::RawCommand(raw) => lines.push(guard.wrap(raw.clone())),
                IrStmt::MacroCommand {
                    template,
                    placeholders,
                } => {
                    let mut stmt_lines = Vec::new();
                    self.emit_macro_command(
                        function,
                        depth,
                        template,
                        placeholders,
                        &mut stmt_lines,
                    );
                    self.extend_guarded(lines, guard, stmt_lines);
                }
                IrStmt::Expr(expr) => {
                    let scratch = self.new_temp();
                    let mut stmt_lines = Vec::new();
                    self.compile_expr_into_named_slot(
                        function,
                        depth,
                        expr,
                        &scratch,
                        &mut stmt_lines,
                    );
                    self.extend_guarded(lines, guard, stmt_lines);
                }
                IrStmt::Return(expr) => {
                    let mut stmt_lines = Vec::new();
                    if let Some(expr) = expr {
                        let slot = return_slot(depth, &function.name, &expr.ty);
                        self.compile_expr_into_slot(function, depth, expr, &slot, &mut stmt_lines);
                    }
                    stmt_lines.push(format!(
                        "scoreboard players set {} mcfc 1",
                        control_slot(depth, &function.name)
                    ));
                    self.extend_guarded(lines, guard, stmt_lines);
                    return;
                }
                IrStmt::Break => {
                    let Some(loop_ctx) = loop_ctx else {
                        continue;
                    };
                    lines.push(guard.wrap(format!(
                        "scoreboard players set {} mcfc 1",
                        loop_ctx.break_slot
                    )));
                    return;
                }
                IrStmt::Continue => {
                    let Some(loop_ctx) = loop_ctx else {
                        continue;
                    };
                    lines.push(guard.wrap(format!(
                        "scoreboard players set {} mcfc 1",
                        loop_ctx.continue_slot
                    )));
                    return;
                }
                IrStmt::If {
                    condition,
                    then_body,
                    else_body,
                } => {
                    let cond_temp = self.new_temp();
                    let mut stmt_lines = Vec::new();
                    self.compile_expr_into_named_slot(
                        function,
                        depth,
                        condition,
                        &cond_temp,
                        &mut stmt_lines,
                    );
                    self.extend_guarded(lines, guard, stmt_lines);

                    let (then_path, then_name) = self.new_block(function, depth, "if_then");
                    let mut then_lines = Vec::new();
                    self.emit_stmt_list(
                        function,
                        depth,
                        then_body,
                        guard,
                        loop_ctx,
                        &mut then_lines,
                    );
                    self.files.insert(
                        then_path,
                        if then_lines.is_empty() {
                            "# empty if block\n".to_string()
                        } else {
                            then_lines.join("\n") + "\n"
                        },
                    );
                    lines.push(guard.wrap(format!(
                        "execute if score {} mcfc matches 1 run function {}:{}",
                        numeric_slot(depth, &function.name, &cond_temp),
                        self.namespace,
                        then_name
                    )));

                    if !else_body.is_empty() {
                        let (else_path, else_name) = self.new_block(function, depth, "if_else");
                        let mut else_lines = Vec::new();
                        self.emit_stmt_list(
                            function,
                            depth,
                            else_body,
                            guard,
                            loop_ctx,
                            &mut else_lines,
                        );
                        self.files.insert(
                            else_path,
                            if else_lines.is_empty() {
                                "# empty else block\n".to_string()
                            } else {
                                else_lines.join("\n") + "\n"
                            },
                        );
                        lines.push(guard.wrap(format!(
                            "execute unless score {} mcfc matches 1 run function {}:{}",
                            numeric_slot(depth, &function.name, &cond_temp),
                            self.namespace,
                            else_name
                        )));
                    }
                }
                IrStmt::While { condition, body } => {
                    let break_slot = numeric_slot(depth, &function.name, &self.new_temp());
                    let continue_slot = numeric_slot(depth, &function.name, &self.new_temp());
                    let (cond_path, cond_name) = self.new_block(function, depth, "while_cond");
                    let (body_path, body_name) = self.new_block(function, depth, "while_body");

                    let loop_ctx = LoopContext {
                        break_slot: break_slot.clone(),
                        continue_slot: continue_slot.clone(),
                        continue_target: cond_name.clone(),
                    };
                    let loop_guard = guard.within_loop(&loop_ctx);

                    let mut cond_lines = vec![loop_guard.wrap_allow_continue(format!(
                        "scoreboard players set {} mcfc 0",
                        continue_slot
                    ))];
                    let cond_temp = self.new_temp();
                    let mut cond_eval = Vec::new();
                    self.compile_expr_into_named_slot(
                        function,
                        depth,
                        condition,
                        &cond_temp,
                        &mut cond_eval,
                    );
                    self.extend_guarded_allow_continue(&mut cond_lines, &loop_guard, cond_eval);
                    cond_lines.push(loop_guard.wrap_allow_continue(format!(
                        "execute if score {} mcfc matches 1 run function {}:{}",
                        numeric_slot(depth, &function.name, &cond_temp),
                        self.namespace,
                        body_name
                    )));

                    let mut body_lines = Vec::new();
                    self.emit_stmt_list(
                        function,
                        depth,
                        body,
                        &loop_guard,
                        Some(&loop_ctx),
                        &mut body_lines,
                    );
                    body_lines.push(loop_guard.wrap_allow_continue(format!(
                        "function {}:{}",
                        self.namespace, loop_ctx.continue_target
                    )));

                    self.files.insert(cond_path, cond_lines.join("\n") + "\n");
                    self.files.insert(
                        body_path,
                        if body_lines.is_empty() {
                            "# empty while body\n".to_string()
                        } else {
                            body_lines.join("\n") + "\n"
                        },
                    );

                    lines.push(guard.wrap(format!("scoreboard players set {} mcfc 0", break_slot)));
                    lines.push(
                        guard.wrap(format!("scoreboard players set {} mcfc 0", continue_slot)),
                    );
                    lines.push(guard.wrap(format!("function {}:{}", self.namespace, cond_name)));
                }
                IrStmt::For {
                    name,
                    start,
                    end,
                    inclusive,
                    body,
                } => {
                    let break_slot = numeric_slot(depth, &function.name, &self.new_temp());
                    let continue_slot = numeric_slot(depth, &function.name, &self.new_temp());
                    let end_name = self.new_temp();
                    let cond_temp = self.new_temp();
                    let (cond_path, cond_name) = self.new_block(function, depth, "for_cond");
                    let (body_path, body_name) = self.new_block(function, depth, "for_body");
                    let (step_path, step_name) = self.new_block(function, depth, "for_step");

                    let loop_ctx = LoopContext {
                        break_slot: break_slot.clone(),
                        continue_slot: continue_slot.clone(),
                        continue_target: step_name.clone(),
                    };
                    let loop_guard = guard.within_loop(&loop_ctx);

                    let mut init_lines = Vec::new();
                    self.compile_expr_into_named_slot(
                        function,
                        depth,
                        start,
                        name,
                        &mut init_lines,
                    );
                    self.compile_expr_into_named_slot(
                        function,
                        depth,
                        end,
                        &end_name,
                        &mut init_lines,
                    );
                    self.extend_guarded(lines, guard, init_lines);
                    lines.push(guard.wrap(format!("scoreboard players set {} mcfc 0", break_slot)));
                    lines.push(
                        guard.wrap(format!("scoreboard players set {} mcfc 0", continue_slot)),
                    );

                    let cmp_op = if *inclusive {
                        BinaryOp::Lte
                    } else {
                        BinaryOp::Lt
                    };
                    let cond_expr = IrExpr {
                        ty: Type::Bool,
                        kind: IrExprKind::Binary {
                            op: cmp_op,
                            left: Box::new(IrExpr {
                                ty: Type::Int,
                                kind: IrExprKind::Variable(name.clone()),
                            }),
                            right: Box::new(IrExpr {
                                ty: Type::Int,
                                kind: IrExprKind::Variable(end_name.clone()),
                            }),
                        },
                    };

                    let mut cond_lines = Vec::new();
                    let mut cond_eval = Vec::new();
                    self.compile_expr_into_named_slot(
                        function,
                        depth,
                        &cond_expr,
                        &cond_temp,
                        &mut cond_eval,
                    );
                    self.extend_guarded(&mut cond_lines, &loop_guard, cond_eval);
                    cond_lines.push(loop_guard.wrap(format!(
                        "execute if score {} mcfc matches 1 run function {}:{}",
                        numeric_slot(depth, &function.name, &cond_temp),
                        self.namespace,
                        body_name
                    )));

                    let mut body_lines = Vec::new();
                    self.emit_stmt_list(
                        function,
                        depth,
                        body,
                        &loop_guard,
                        Some(&loop_ctx),
                        &mut body_lines,
                    );
                    body_lines.push(loop_guard.wrap_allow_continue(format!(
                        "function {}:{}",
                        self.namespace, loop_ctx.continue_target
                    )));

                    let mut step_lines = vec![loop_guard.wrap_allow_continue(format!(
                        "scoreboard players set {} mcfc 0",
                        continue_slot
                    ))];
                    step_lines.push(loop_guard.wrap_allow_continue(format!(
                        "scoreboard players add {} mcfc 1",
                        numeric_slot(depth, &function.name, name)
                    )));
                    step_lines.push(
                        loop_guard.wrap_allow_continue(format!(
                            "function {}:{}",
                            self.namespace, cond_name
                        )),
                    );

                    self.files.insert(cond_path, cond_lines.join("\n") + "\n");
                    self.files.insert(
                        body_path,
                        if body_lines.is_empty() {
                            "# empty for body\n".to_string()
                        } else {
                            body_lines.join("\n") + "\n"
                        },
                    );
                    self.files.insert(step_path, step_lines.join("\n") + "\n");

                    lines.push(guard.wrap(format!("function {}:{}", self.namespace, cond_name)));
                }
            }
        }
    }

    fn extend_guarded(&self, target: &mut Vec<String>, guard: &Guard, lines: Vec<String>) {
        target.extend(lines.into_iter().map(|line| guard.wrap(line)));
    }

    fn extend_guarded_allow_continue(
        &self,
        target: &mut Vec<String>,
        guard: &Guard,
        lines: Vec<String>,
    ) {
        target.extend(
            lines
                .into_iter()
                .map(|line| guard.wrap_allow_continue(line)),
        );
    }

    fn compile_expr_into_named_slot(
        &mut self,
        function: &IrFunction,
        depth: usize,
        expr: &IrExpr,
        name: &str,
        lines: &mut Vec<String>,
    ) {
        let slot = local_slot(depth, &function.name, name, &expr.ty);
        self.compile_expr_into_slot(function, depth, expr, &slot, lines);
    }

    fn compile_expr_into_slot(
        &mut self,
        function: &IrFunction,
        depth: usize,
        expr: &IrExpr,
        target: &SlotRef,
        lines: &mut Vec<String>,
    ) {
        match &expr.kind {
            IrExprKind::Int(value) => lines.push(format!(
                "scoreboard players set {} mcfc {}",
                target.numeric_name(),
                value
            )),
            IrExprKind::Bool(value) => lines.push(format!(
                "scoreboard players set {} mcfc {}",
                target.numeric_name(),
                if *value { 1 } else { 0 }
            )),
            IrExprKind::String(value) => lines.push(format!(
                "data modify storage {}:runtime {} set value {}",
                self.namespace,
                target.storage_path(),
                quoted(value)
            )),
            IrExprKind::Variable(name) => match expr.ty {
                Type::Int | Type::Bool => lines.push(format!(
                    "scoreboard players operation {} mcfc = {} mcfc",
                    target.numeric_name(),
                    numeric_slot(depth, &function.name, name)
                )),
                Type::String => lines.push(format!(
                    "data modify storage {}:runtime {} set from storage {}:runtime {}",
                    self.namespace,
                    target.storage_path(),
                    self.namespace,
                    string_slot(depth, &function.name, name)
                )),
                Type::Void => {}
            },
            IrExprKind::Unary { op, expr } => {
                self.compile_unary(function, depth, *op, expr, target, lines);
            }
            IrExprKind::Binary { op, left, right } => {
                self.compile_binary(function, depth, *op, left, right, target, lines);
            }
            IrExprKind::Call {
                function: callee,
                args,
            } => {
                let callee_depth = depth + 1;
                if let Some(info) = self.functions.get(callee).cloned() {
                    lines.push(format!(
                        "scoreboard players set {} mcfc 0",
                        control_slot(callee_depth, callee)
                    ));
                    for ((param_name, param_ty), arg) in info.params.iter().zip(args.iter()) {
                        let param_slot = local_slot(callee_depth, callee, param_name, param_ty);
                        self.compile_expr_into_slot(function, depth, arg, &param_slot, lines);
                    }
                    lines.push(format!(
                        "function {}:{}",
                        self.namespace,
                        self.function_entry_name(callee, callee_depth)
                    ));
                    match expr.ty {
                        Type::Int | Type::Bool => lines.push(format!(
                            "scoreboard players operation {} mcfc = {} mcfc",
                            target.numeric_name(),
                            numeric_return_slot(callee_depth, callee)
                        )),
                        Type::String => lines.push(format!(
                            "data modify storage {}:runtime {} set from storage {}:runtime {}",
                            self.namespace,
                            target.storage_path(),
                            self.namespace,
                            string_return_slot(callee_depth, callee)
                        )),
                        Type::Void => {}
                    }
                }
            }
        }
    }

    fn compile_unary(
        &mut self,
        function: &IrFunction,
        depth: usize,
        op: UnaryOp,
        expr: &IrExpr,
        target: &SlotRef,
        lines: &mut Vec<String>,
    ) {
        let temp = self.new_temp();
        let temp_slot = local_slot(depth, &function.name, &temp, &expr.ty);
        self.compile_expr_into_slot(function, depth, expr, &temp_slot, lines);

        match op {
            UnaryOp::Not => {
                lines.push(format!(
                    "scoreboard players set {} mcfc 1",
                    target.numeric_name()
                ));
                lines.push(format!(
                    "execute if score {} mcfc matches 1 run scoreboard players set {} mcfc 0",
                    temp_slot.numeric_name(),
                    target.numeric_name()
                ));
            }
        }
    }

    fn compile_binary(
        &mut self,
        function: &IrFunction,
        depth: usize,
        op: BinaryOp,
        left: &IrExpr,
        right: &IrExpr,
        target: &SlotRef,
        lines: &mut Vec<String>,
    ) {
        match op {
            BinaryOp::And => {
                let left_temp = self.new_temp();
                let left_slot = local_slot(depth, &function.name, &left_temp, &left.ty);
                self.compile_expr_into_slot(function, depth, left, &left_slot, lines);
                lines.push(format!(
                    "scoreboard players set {} mcfc 0",
                    target.numeric_name()
                ));
                let (rhs_path, rhs_name) = self.new_block(function, depth, "logic_and_rhs");
                let mut rhs_lines = Vec::new();
                self.compile_expr_into_slot(function, depth, right, target, &mut rhs_lines);
                self.files.insert(rhs_path, rhs_lines.join("\n") + "\n");
                lines.push(format!(
                    "execute if score {} mcfc matches 1 run function {}:{}",
                    left_slot.numeric_name(),
                    self.namespace,
                    rhs_name
                ));
                return;
            }
            BinaryOp::Or => {
                let left_temp = self.new_temp();
                let left_slot = local_slot(depth, &function.name, &left_temp, &left.ty);
                self.compile_expr_into_slot(function, depth, left, &left_slot, lines);
                lines.push(format!(
                    "scoreboard players set {} mcfc 1",
                    target.numeric_name()
                ));
                let (rhs_path, rhs_name) = self.new_block(function, depth, "logic_or_rhs");
                let mut rhs_lines = Vec::new();
                self.compile_expr_into_slot(function, depth, right, target, &mut rhs_lines);
                self.files.insert(rhs_path, rhs_lines.join("\n") + "\n");
                lines.push(format!(
                    "execute if score {} mcfc matches 0 run function {}:{}",
                    left_slot.numeric_name(),
                    self.namespace,
                    rhs_name
                ));
                return;
            }
            _ => {}
        }

        let left_temp = self.new_temp();
        let right_temp = self.new_temp();
        let left_slot = local_slot(depth, &function.name, &left_temp, &left.ty);
        let right_slot = local_slot(depth, &function.name, &right_temp, &right.ty);
        self.compile_expr_into_slot(function, depth, left, &left_slot, lines);
        self.compile_expr_into_slot(function, depth, right, &right_slot, lines);

        match op {
            BinaryOp::Add | BinaryOp::Sub | BinaryOp::Mul | BinaryOp::Div => {
                lines.push(format!(
                    "scoreboard players operation {} mcfc = {} mcfc",
                    target.numeric_name(),
                    left_slot.numeric_name()
                ));
                let operator = match op {
                    BinaryOp::Add => "+=",
                    BinaryOp::Sub => "-=",
                    BinaryOp::Mul => "*=",
                    BinaryOp::Div => "/=",
                    _ => unreachable!(),
                };
                lines.push(format!(
                    "scoreboard players operation {} mcfc {} {} mcfc",
                    target.numeric_name(),
                    operator,
                    right_slot.numeric_name()
                ));
            }
            BinaryOp::Eq | BinaryOp::NotEq
                if matches!(left.ty, Type::String) && matches!(right.ty, Type::String) =>
            {
                self.compile_string_equality(op, &left_slot, &right_slot, target, lines);
            }
            BinaryOp::Eq
            | BinaryOp::NotEq
            | BinaryOp::Lt
            | BinaryOp::Lte
            | BinaryOp::Gt
            | BinaryOp::Gte => {
                lines.push(format!(
                    "scoreboard players set {} mcfc 0",
                    target.numeric_name()
                ));
                let (keyword, operator) = match op {
                    BinaryOp::Eq => ("if", "="),
                    BinaryOp::NotEq => ("unless", "="),
                    BinaryOp::Lt => ("if", "<"),
                    BinaryOp::Lte => ("if", "<="),
                    BinaryOp::Gt => ("if", ">"),
                    BinaryOp::Gte => ("if", ">="),
                    _ => unreachable!(),
                };
                lines.push(format!(
                    "execute {} score {} mcfc {} {} mcfc run scoreboard players set {} mcfc 1",
                    keyword,
                    left_slot.numeric_name(),
                    operator,
                    right_slot.numeric_name(),
                    target.numeric_name()
                ));
            }
            BinaryOp::And | BinaryOp::Or => unreachable!(),
        }
    }

    fn compile_string_equality(
        &mut self,
        op: BinaryOp,
        left_slot: &SlotRef,
        right_slot: &SlotRef,
        target: &SlotRef,
        lines: &mut Vec<String>,
    ) {
        let compare_storage = format!("frames.__cmp{}", self.new_temp());
        let compare_result = numeric_slot(0, "__cmp", &self.new_temp());
        lines.push(format!(
            "data modify storage {}:runtime {} set from storage {}:runtime {}",
            self.namespace,
            compare_storage,
            self.namespace,
            left_slot.storage_path()
        ));
        lines.push(format!(
            "execute store success score {} mcfc run data modify storage {}:runtime {} set from storage {}:runtime {}",
            compare_result,
            self.namespace,
            compare_storage,
            self.namespace,
            right_slot.storage_path()
        ));

        match op {
            BinaryOp::Eq => {
                lines.push(format!(
                    "scoreboard players set {} mcfc 1",
                    target.numeric_name()
                ));
                lines.push(format!(
                    "execute if score {} mcfc matches 1 run scoreboard players set {} mcfc 0",
                    compare_result,
                    target.numeric_name()
                ));
            }
            BinaryOp::NotEq => {
                lines.push(format!(
                    "scoreboard players set {} mcfc 0",
                    target.numeric_name()
                ));
                lines.push(format!(
                    "execute if score {} mcfc matches 1 run scoreboard players set {} mcfc 1",
                    compare_result,
                    target.numeric_name()
                ));
            }
            _ => unreachable!(),
        }
    }

    fn function_entry_name(&self, function: &str, depth: usize) -> String {
        format!("generated/{}__d{}__entry", sanitize(function), depth)
    }

    fn emit_macro_command(
        &mut self,
        function: &IrFunction,
        depth: usize,
        template: &str,
        placeholders: &[IrMacroPlaceholder],
        lines: &mut Vec<String>,
    ) {
        self.macro_counter += 1;
        let macro_id = self.macro_counter;
        let relative = format!(
            "generated/{}__d{}__macro_{}",
            sanitize(&function.name),
            depth,
            macro_id
        );
        let path = format!("data/{}/function/{}.mcfunction", self.namespace, relative);
        self.files.insert(path, format!("${}\n", template));

        let storage_base = macro_storage_base(depth, &function.name, macro_id);
        for placeholder in placeholders {
            let source_slot = local_slot(depth, &function.name, &placeholder.name, &placeholder.ty);
            let target_path = format!("{}.{}", storage_base, sanitize(&placeholder.name));
            match placeholder.ty {
                Type::Int | Type::Bool => lines.push(format!(
                    "execute store result storage {}:runtime {} int 1 run scoreboard players get {} mcfc",
                    self.namespace,
                    target_path,
                    source_slot.numeric_name()
                )),
                Type::String => lines.push(format!(
                    "data modify storage {}:runtime {} set from storage {}:runtime {}",
                    self.namespace,
                    target_path,
                    self.namespace,
                    source_slot.storage_path()
                )),
                Type::Void => {}
            }
        }
        lines.push(format!(
            "function {}:{} with storage {}:runtime {}",
            self.namespace, relative, self.namespace, storage_base
        ));
    }

    fn function_entry_path(&self, function: &str, depth: usize) -> String {
        format!(
            "data/{}/function/{}.mcfunction",
            self.namespace,
            self.function_entry_name(function, depth)
        )
    }

    fn new_block(&mut self, function: &IrFunction, depth: usize, label: &str) -> (String, String) {
        self.block_counter += 1;
        let relative = format!(
            "generated/{}__d{}__{}_{}",
            sanitize(&function.name),
            depth,
            label,
            self.block_counter
        );
        (
            format!("data/{}/function/{}.mcfunction", self.namespace, relative),
            relative,
        )
    }

    fn new_temp(&mut self) -> String {
        self.temp_counter += 1;
        format!("__tmp{}", self.temp_counter)
    }

    fn render_book_dispatch_calls(&self) -> String {
        let mut lines = String::new();
        for name in self.book_commands.keys() {
            lines.push_str(&format!(
                "execute if data storage {}:runtime {{book:{{command_name:\"{}\"}}}} run function {}:generated/book/dispatch_{}\n",
                self.namespace,
                name,
                self.namespace,
                sanitize(name)
            ));
        }
        lines
    }

    fn emit_book_dispatch_function(&mut self, command: &IrBookCommand) {
        let Some(function) = self.functions.get(&command.function_name) else {
            return;
        };

        let expected_tokens = command.arg_count + 1;
        let mut lines = vec![
            "scoreboard players set $book_dispatch_matched mcfc 1".to_string(),
            format!(
                "execute unless score $book_token_count mcfc matches {} run tellraw @s \"Wrong argument count for {}\"",
                expected_tokens, command.function_name
            ),
        ];

        let mut final_conditions = vec![format!(
            "execute if score $book_token_count mcfc matches {}",
            expected_tokens
        )];

        for index in 0..command.arg_count {
            let token_index = index + 1;
            let param_name = &function.params[index].0;
            lines.push(format!(
                "execute if score $book_token_count mcfc matches {} run data modify storage {}:runtime book.dispatch.arg set from storage {}:runtime book.tokens[{}]",
                expected_tokens, self.namespace, self.namespace, token_index
            ));
            lines.push(format!(
                "execute if score $book_token_count mcfc matches {} store success score $book_parse_{} mcfc run function {}:generated/book/parse_arg_{} with storage {}:runtime book.dispatch",
                expected_tokens, token_index, self.namespace, token_index, self.namespace
            ));
            lines.push(format!(
                "execute if score $book_token_count mcfc matches {} unless score $book_parse_{} mcfc matches 1 run tellraw @s \"Invalid integer argument {} for {}\"",
                expected_tokens, token_index, token_index, command.function_name
            ));
            lines.push(format!(
                "execute if score $book_token_count mcfc matches {} if score $book_parse_{} mcfc matches 1 run scoreboard players operation {} mcfc = $book_arg{} mcfc",
                expected_tokens,
                token_index,
                numeric_slot(0, &command.function_name, param_name),
                token_index
            ));
            final_conditions.push(format!(
                "if score $book_parse_{} mcfc matches 1",
                token_index
            ));
        }

        lines.push(format!(
            "{} run function {}:{}",
            final_conditions.join(" "),
            self.namespace,
            self.function_entry_name(&command.function_name, 0)
        ));

        self.files.insert(
            format!(
                "data/{}/function/generated/book/dispatch_{}.mcfunction",
                self.namespace,
                sanitize(&command.function_name)
            ),
            lines.join("\n") + "\n",
        );
    }
}

#[derive(Debug, Clone)]
struct SlotRef {
    name: String,
}

impl SlotRef {
    fn numeric_name(&self) -> &str {
        &self.name
    }

    fn storage_path(&self) -> &str {
        &self.name
    }
}

fn local_slot(depth: usize, function: &str, name: &str, ty: &Type) -> SlotRef {
    match ty {
        Type::Int | Type::Bool => SlotRef {
            name: numeric_slot(depth, function, name),
        },
        Type::String => SlotRef {
            name: string_slot(depth, function, name),
        },
        Type::Void => SlotRef {
            name: "__void".to_string(),
        },
    }
}

fn return_slot(depth: usize, function: &str, ty: &Type) -> SlotRef {
    match ty {
        Type::Int | Type::Bool => SlotRef {
            name: numeric_return_slot(depth, function),
        },
        Type::String => SlotRef {
            name: string_return_slot(depth, function),
        },
        Type::Void => SlotRef {
            name: "__void".to_string(),
        },
    }
}

fn control_slot(depth: usize, function: &str) -> String {
    format!("$d{}_{}__ctrl", depth, sanitize(function))
}

fn numeric_slot(depth: usize, function: &str, name: &str) -> String {
    format!("$d{}_{}_{}", depth, sanitize(function), sanitize(name))
}

fn numeric_return_slot(depth: usize, function: &str) -> String {
    format!("$d{}_{}__ret", depth, sanitize(function))
}

fn string_slot(depth: usize, function: &str, name: &str) -> String {
    format!(
        "frames.d{}.{}.{}",
        depth,
        sanitize(function),
        sanitize(name)
    )
}

fn string_return_slot(depth: usize, function: &str) -> String {
    format!("frames.d{}.{}.__ret", depth, sanitize(function))
}

fn sanitize(value: &str) -> String {
    value
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

fn quoted(value: &str) -> String {
    format!("{:?}", value)
}

fn macro_storage_base(depth: usize, function: &str, macro_id: usize) -> String {
    format!(
        "frames.d{}.{}.__macro{}",
        depth,
        sanitize(function),
        macro_id
    )
}
