#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MinecraftIdCategory {
    Block,
    Item,
    Entity,
    LootTable,
    Particle,
    SoundEvent,
    Effect,
}

include!(concat!(env!("OUT_DIR"), "/minecraft_ids.rs"));

pub fn ids_for_category(category: MinecraftIdCategory) -> &'static [&'static str] {
    match category {
        MinecraftIdCategory::Block => BLOCK_IDS,
        MinecraftIdCategory::Item => ITEM_IDS,
        MinecraftIdCategory::Entity => ENTITY_IDS,
        MinecraftIdCategory::LootTable => LOOT_TABLE_IDS,
        MinecraftIdCategory::Particle => PARTICLE_IDS,
        MinecraftIdCategory::SoundEvent => SOUND_EVENT_IDS,
        MinecraftIdCategory::Effect => EFFECT_IDS,
    }
}

/// Every block state property in Minecraft 26.3 with all its values, from
/// https://raw.githubusercontent.com/misode/mcmeta/26.3-summary/blocks/data.json.
pub static BLOCK_PROPERTIES: &[(&str, &[&str])] = &[
    (
        "age",
        &[
            "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15",
            "16", "17", "18", "19", "20", "21", "22", "23", "24", "25",
        ],
    ),
    ("attached", &["true", "false"]),
    (
        "attachment",
        &["floor", "ceiling", "single_wall", "double_wall"],
    ),
    ("axis", &["x", "y", "z"]),
    ("berries", &["true", "false"]),
    ("bites", &["0", "1", "2", "3", "4", "5", "6"]),
    ("bloom", &["true", "false"]),
    ("bottom", &["true", "false"]),
    ("can_summon", &["true", "false"]),
    ("candles", &["1", "2", "3", "4"]),
    ("charges", &["0", "1", "2", "3", "4"]),
    ("conditional", &["true", "false"]),
    (
        "copper_golem_pose",
        &["standing", "sitting", "running", "star"],
    ),
    ("cracked", &["true", "false"]),
    ("crafting", &["true", "false"]),
    ("creaking_heart_state", &["uprooted", "dormant", "awake"]),
    ("delay", &["1", "2", "3", "4"]),
    ("disarmed", &["true", "false"]),
    ("distance", &["1", "2", "3", "4", "5", "6", "7", "0"]),
    ("down", &["true", "false"]),
    ("drag", &["true", "false"]),
    ("dusted", &["0", "1", "2", "3"]),
    (
        "east",
        &["true", "false", "none", "low", "tall", "up", "side"],
    ),
    ("eggs", &["1", "2", "3", "4"]),
    ("enabled", &["true", "false"]),
    ("extended", &["true", "false"]),
    ("eye", &["true", "false"]),
    ("face", &["floor", "wall", "ceiling"]),
    ("facing", &["north", "south", "west", "east", "up", "down"]),
    ("flower_amount", &["1", "2", "3", "4"]),
    ("half", &["upper", "lower", "top", "bottom"]),
    ("hanging", &["true", "false"]),
    ("has_book", &["true", "false"]),
    ("has_bottle_0", &["true", "false"]),
    ("has_bottle_1", &["true", "false"]),
    ("has_bottle_2", &["true", "false"]),
    ("has_record", &["true", "false"]),
    ("hatch", &["0", "1", "2"]),
    ("hinge", &["left", "right"]),
    ("honey_level", &["0", "1", "2", "3", "4", "5"]),
    ("hydration", &["0", "1", "2", "3"]),
    ("in_wall", &["true", "false"]),
    (
        "instrument",
        &[
            "harp",
            "basedrum",
            "snare",
            "hat",
            "bass",
            "flute",
            "bell",
            "guitar",
            "chime",
            "xylophone",
            "iron_xylophone",
            "cow_bell",
            "didgeridoo",
            "bit",
            "banjo",
            "pling",
            "trumpet",
            "trumpet_exposed",
            "trumpet_oxidized",
            "trumpet_weathered",
            "zombie",
            "skeleton",
            "creeper",
            "dragon",
            "wither_skeleton",
            "piglin",
            "custom_head",
        ],
    ),
    ("inverted", &["true", "false"]),
    ("layers", &["1", "2", "3", "4", "5", "6", "7", "8"]),
    ("leaves", &["none", "small", "large"]),
    (
        "level",
        &[
            "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15",
        ],
    ),
    ("lit", &["true", "false"]),
    ("locked", &["true", "false"]),
    (
        "mode",
        &[
            "compare", "subtract", "save", "load", "corner", "data", "start", "log", "fail",
            "accept",
        ],
    ),
    ("moisture", &["0", "1", "2", "3", "4", "5", "6", "7"]),
    ("natural", &["true", "false"]),
    (
        "north",
        &["true", "false", "none", "low", "tall", "up", "side"],
    ),
    (
        "note",
        &[
            "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15",
            "16", "17", "18", "19", "20", "21", "22", "23", "24",
        ],
    ),
    ("occupied", &["true", "false"]),
    ("ominous", &["true", "false"]),
    ("open", &["true", "false"]),
    (
        "orientation",
        &[
            "down_east",
            "down_north",
            "down_south",
            "down_west",
            "up_east",
            "up_north",
            "up_south",
            "up_west",
            "west_up",
            "east_up",
            "north_up",
            "south_up",
        ],
    ),
    ("part", &["head", "foot"]),
    ("persistent", &["true", "false"]),
    ("pickles", &["1", "2", "3", "4"]),
    (
        "potent_sulfur_state",
        &["dry", "wet", "dormant", "erupting", "continuous"],
    ),
    (
        "power",
        &[
            "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15",
        ],
    ),
    ("powered", &["true", "false"]),
    (
        "rotation",
        &[
            "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15",
        ],
    ),
    ("sculk_sensor_phase", &["inactive", "active", "cooldown"]),
    ("segment_amount", &["1", "2", "3", "4"]),
    (
        "shape",
        &[
            "straight",
            "inner_left",
            "inner_right",
            "outer_left",
            "outer_right",
            "north_south",
            "east_west",
            "ascending_east",
            "ascending_west",
            "ascending_north",
            "ascending_south",
            "south_east",
            "south_west",
            "north_west",
            "north_east",
        ],
    ),
    ("short", &["true", "false"]),
    ("shrieking", &["true", "false"]),
    ("side_chain", &["unconnected", "right", "center", "left"]),
    ("signal_fire", &["true", "false"]),
    ("slot_0_occupied", &["true", "false"]),
    ("slot_1_occupied", &["true", "false"]),
    ("slot_2_occupied", &["true", "false"]),
    ("slot_3_occupied", &["true", "false"]),
    ("slot_4_occupied", &["true", "false"]),
    ("slot_5_occupied", &["true", "false"]),
    ("snowy", &["true", "false"]),
    (
        "south",
        &["true", "false", "none", "low", "tall", "up", "side"],
    ),
    ("stage", &["0", "1"]),
    (
        "thickness",
        &["tip_merge", "tip", "frustum", "middle", "base"],
    ),
    ("tilt", &["none", "unstable", "partial", "full"]),
    ("tip", &["true", "false"]),
    (
        "trial_spawner_state",
        &[
            "inactive",
            "waiting_for_players",
            "active",
            "waiting_for_reward_ejection",
            "ejecting_reward",
            "cooldown",
        ],
    ),
    ("triggered", &["true", "false"]),
    (
        "type",
        &[
            "top", "bottom", "double", "single", "left", "right", "normal", "sticky",
        ],
    ),
    ("unstable", &["true", "false"]),
    ("up", &["true", "false"]),
    (
        "vault_state",
        &["inactive", "active", "unlocking", "ejecting"],
    ),
    ("vertical_direction", &["up", "down"]),
    ("waterlogged", &["true", "false"]),
    (
        "west",
        &["true", "false", "none", "low", "tall", "up", "side"],
    ),
];
